name: Ping Website
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  ping:
    runs-on: ubunto-latest
    steps:
      - name: Ping the site
        run: curl -I https://www.patertechnologies.com.br/blog/
