name: Keep Alive
on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar ping para Render
        run: |
          curl -s https://www.patertechnologies.com.br/blog/
